server:
  port: 8081

spring:
  #db
  h2:
    console:
      enabled: true
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# tg
app:
  http:
    bot: change-me
  telegram:
    name: "${TG_NAME}"
    token: "${TG_TOKEN}"
